# Generated by Django 4.2.dev20220526083951 on 2022-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to='books_covers'),
            preserve_default=False,
        ),
    ]
